### PR TITLE
bugfix, initializing ClusterPool with password

### PR DESCRIPTION
**Pull request by tarcisioN**
it should pass the password attribute to ClusterMap in order to properly open a connection in ClusterMap._fetch_map method

### CODE REVIEW

**Comment by schlitzered** [comment]
Thanks for contributing!

AFAIK: i did not implement passing a password to ClusterMap because RedisCluster did not support authentication back then, has this changed? doing a quick search i was not able to find anything related to it.

The same goes for Sentinels, they did not support authentication. but it seems at least for sentinels this has changed, see: https://github.com/antirez/redis/issues/3279.

So yes, i would really appreciate if you adjust the SentinelPools to pass the password.

**Comment by schlitzered** [comment]
okay, the pull request looks fine so far. but i will wait for you to make the sentinel adjustments.

**Comment by tarcisioN** [comment]
I did the adjustments in SentinelPool as expected, 
but I did realize, during my tests, that in a case of a new master election the connection fail, needing a new 'pool.acquire()' to select the new master. Is this the expected behavior?

**Comment by schlitzered** [comment]
yes, this is expected, if a master fails, all unused connections of the pool will be closed.. all connections in use will fail and when returned to the pool also get closed.

i am currently reviewing the change, i noted that "SentinelClient" also should accept "sentinel_password", but i can add this.

**Comment by tarcisioN** [comment]
> i am currently reviewing the change, i noted that "SentinelClient" also should accept "sentinel_password", but i can add this.
 It accepts,  but for him the parameter is just "password"

**Comment by schlitzered** [comment]
ahh yes, makes sense, i was just confused. :-)

**Comment by schlitzered** [comment]
new release published https://pypi.org/project/python-redis/

**Pull request merged**
